name: "Style Check"
description: "Check code style using clang-format"

runs:
  using: "composite"
  steps:
    - name: "run clang-format"
      shell: bash
      run: |
        PROJECT_PATH="$(pwd)"
        SOURCE_FILES=$(find "$PROJECT_PATH/src" "$PROJECT_PATH/include" -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \))

        ERROR_FILE_FLAG=$PROJECT_PATH/clang_format_errors.txt

        echo "Running: clang-format -n $SOURCE_FILES"

        CLANG_COMMAND=$(clang-format -n $SOURCE_FILES 2> ${ERROR_FILE_FLAG})

        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: There are some files that are not formatted correctly"
            cat $ERROR_FILE_FLAG
            exit 1
        else
            echo "All files are formatted correctly. Niiiceee"
            exit 0
        fi

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Clang-format errors
        path: ./clang_format_errors.txt
        retention-days: 1
