name: "Build"
description: "Compile the project"

runs:
  using: "composite"
  steps:
    # Instalar dependencias del sistema
    - name: "Install system dependencies"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libmicrohttpd-dev python3-venv

    # Clonar y compilar Prometheus client
    - name: "Clone prometheus client"
      shell: bash
      run: |
        git clone https://github.com/digitalocean/prometheus-client-c.git
        cd prometheus-client-c
        rm -rf promhttp

    - name: "Build and install Prometheus client"
      shell: bash
      run: |
        cd prometheus-client-c/prom
        mkdir -p build
        cd build
        cmake ..
        make
        sudo make install

    # Crear venv y Conan
    - name: "Create venv"
      shell: bash
      run: python3 -m venv .venv

    - name: "Activate venv and install Conan"
      shell: bash
      run: |
        source .venv/bin/activate
        pip install --upgrade pip
        pip install conan

    - name: "Configure Conan profile"
      shell: bash
      run: |
        source .venv/bin/activate
        conan profile detect


    - name: "Install project dependencies with Conan"
      shell: bash
      run: |
        source .venv/bin/activate
        conan install . --output-folder=. --build=missing

    # Configurar CMake con toolchain de Conan
    - name: "Configure CMake"
      shell: bash
      run: |
        source .venv/bin/activate
        cmake -B build -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

    # Compilar el proyecto
    - name: "Build the project"
      shell: bash
      run: |
        source .venv/bin/activate
        cmake --build build
